#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_MICRO 0

#define TOSTRING(a) #a
#define VERSION_INT(a, b, c) ((a)<<16 | (b)<<8 | (c))
#define VERSION(a, b, c) TOSTRING(a.b.c)

#define LIBTRANS_VERSION VERSION(VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO)
#define LIBTRANS_VERSION_INT VERSION_INT(VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO)

#endif /* VERSION_H */

